export const OWNED_GRAPH_MINIMAP_LEFT_INSET = 12;
export const OWNED_GRAPH_MINIMAP_SIZE = 160;
export const OWNED_GRAPH_MINIMAP_CONTROL_GAP = 12;

export const OWNED_GRAPH_MINIMAP_RESERVED_LEFT =
  OWNED_GRAPH_MINIMAP_LEFT_INSET
  + OWNED_GRAPH_MINIMAP_SIZE
  + OWNED_GRAPH_MINIMAP_CONTROL_GAP;
