import { examplesHref } from './links';

export interface ExampleContent {
  id: string;
  href: string;
  name: string;
  category: 'language' | 'plugin';
  iconUrl: string;
  workspace: string;
  screenshots: {
    dark: string;
    light: string;
  };
  summary: string;
  supported: readonly string[];
  plugin?: {
    id: string;
    packageName: string;
  };
}

export const exampleContent = [
  {
    id: 'typescript',
    href: `${examplesHref}#typescript`,
    name: 'TypeScript',
    category: 'language',
    iconUrl: '/icons/typescript.svg',
    workspace: 'examples/example-typescript',
    screenshots: {
      dark: '/media/examples/dark/typescript.png',
      light: '/media/examples/light/typescript.png',
    },
    summary: 'Runnable palette generator with imports, type imports, exports, dynamic imports, and path aliases.',
    supported: ['imports', 'exports', 'aliases', 'symbols'],
  },
  {
    id: 'javascript',
    href: `${examplesHref}#javascript`,
    name: 'JavaScript',
    category: 'language',
    iconUrl: '/icons/javascript.svg',
    workspace: 'examples/example-javascript',
    screenshots: {
      dark: '/media/examples/dark/javascript.png',
      light: '/media/examples/light/javascript.png',
    },
    summary: 'Small JavaScript workspace mirroring the TypeScript graph story with imports, calls, and inheritance.',
    supported: ['imports', 'calls', 'inheritance', 'symbols'],
  },
  {
    id: 'vue',
    href: `${examplesHref}#vue`,
    name: 'Vue',
    category: 'plugin',
    iconUrl: '/icons/vue.svg',
    workspace: 'examples/example-vue',
    screenshots: {
      dark: '/media/examples/dark/vue.png',
      light: '/media/examples/light/vue.png',
    },
    summary: 'Vue 3 single-file component workspace with script setup, type imports, and async components.',
    supported: ['SFCs', 'components', 'type imports', 'lazy imports'],
    plugin: { id: 'vue', packageName: '@codegraphy-dev/plugin-vue' },
  },
  {
    id: 'svelte',
    href: `${examplesHref}#svelte`,
    name: 'Svelte',
    category: 'plugin',
    iconUrl: '/icons/svelte.svg',
    workspace: 'examples/example-svelte',
    screenshots: {
      dark: '/media/examples/dark/svelte.png',
      light: '/media/examples/light/svelte.png',
    },
    summary: 'Svelte component fixture with module scripts, instance scripts, type imports, and lazy modules.',
    supported: ['components', 'module scripts', 'type imports'],
    plugin: { id: 'svelte', packageName: '@codegraphy-dev/plugin-svelte' },
  },
  {
    id: 'godot',
    href: `${examplesHref}#godot`,
    name: 'Godot',
    category: 'plugin',
    iconUrl: '/icons/godot.svg',
    workspace: 'examples/example-godot',
    screenshots: {
      dark: '/media/examples/dark/godot.png',
      light: '/media/examples/light/godot.png',
    },
    summary: 'Runnable Godot project with scenes, resources, autoloads, GDScript inheritance, and class_name symbols.',
    supported: ['scenes', 'resources', 'autoloads', 'GDScript'],
    plugin: { id: 'godot', packageName: '@codegraphy-dev/plugin-godot' },
  },
  {
    id: 'unity',
    href: `${examplesHref}#unity`,
    name: 'Unity',
    category: 'plugin',
    iconUrl: '/icons/unity.svg',
    workspace: 'examples/example-unity',
    screenshots: {
      dark: '/media/examples/dark/unity.png',
      light: '/media/examples/light/unity.png',
    },
    summary: 'Unity sample with scenes, prefabs, GameObjects, Components, ScriptableObjects, and C# scripts.',
    supported: ['scenes', 'prefabs', 'components', 'references'],
    plugin: { id: 'unity', packageName: '@codegraphy-dev/plugin-unity' },
  },
  {
    id: 'python',
    href: `${examplesHref}#python`,
    name: 'Python',
    category: 'language',
    iconUrl: '/icons/python.svg',
    workspace: 'examples/example-python',
    screenshots: {
      dark: '/media/examples/dark/python.png',
      light: '/media/examples/light/python.png',
    },
    summary: 'Import-resolution workspace with config, services, namespace imports, and inheritance.',
    supported: ['imports', 'members', 'inheritance', 'symbols'],
  },
  {
    id: 'csharp',
    href: `${examplesHref}#csharp`,
    name: 'C#',
    category: 'language',
    iconUrl: '/icons/csharp.svg',
    workspace: 'examples/example-csharp',
    screenshots: {
      dark: '/media/examples/dark/csharp.png',
      light: '/media/examples/light/csharp.png',
    },
    summary: 'Task dispatch workspace with types, members, variables, inheritance, interfaces, and events.',
    supported: ['types', 'members', 'variables', 'inheritance'],
  },
  {
    id: 'java',
    href: `${examplesHref}#java`,
    name: 'Java',
    category: 'language',
    iconUrl: '/icons/java.svg',
    workspace: 'examples/example-java',
    screenshots: {
      dark: '/media/examples/dark/java.png',
      light: '/media/examples/light/java.png',
    },
    summary: 'Compact Java import and inheritance example with classes, interfaces, and method symbols.',
    supported: ['imports', 'classes', 'methods', 'inheritance'],
  },
  {
    id: 'kotlin',
    href: `${examplesHref}#kotlin`,
    name: 'Kotlin',
    category: 'language',
    iconUrl: '/icons/kotlin.svg',
    workspace: 'examples/example-kotlin',
    screenshots: {
      dark: '/media/examples/dark/kotlin.png',
      light: '/media/examples/light/kotlin.png',
    },
    summary: 'Gradle/Kotlin project for imports, simple inheritance, and symbol navigation.',
    supported: ['imports', 'classes', 'interfaces', 'symbols'],
  },
  {
    id: 'scala',
    href: `${examplesHref}#scala`,
    name: 'Scala',
    category: 'language',
    iconUrl: '/icons/scala.svg',
    workspace: 'examples/example-scala',
    screenshots: {
      dark: '/media/examples/dark/scala.png',
      light: '/media/examples/light/scala.png',
    },
    summary: 'Scala app/service/repository/view workspace with import, inheritance, class, object, and trait coverage.',
    supported: ['imports', 'traits', 'objects', 'inheritance'],
  },
  {
    id: 'php',
    href: `${examplesHref}#php`,
    name: 'PHP',
    category: 'language',
    iconUrl: '/icons/php.svg',
    workspace: 'examples/example-php',
    screenshots: {
      dark: '/media/examples/dark/php.png',
      light: '/media/examples/light/php.png',
    },
    summary: 'Namespace/use and inheritance fixture with class and function symbols.',
    supported: ['namespaces', 'use', 'classes', 'inheritance'],
  },
  {
    id: 'ruby',
    href: `${examplesHref}#ruby`,
    name: 'Ruby',
    category: 'language',
    iconUrl: '/icons/ruby.svg',
    workspace: 'examples/example-ruby',
    screenshots: {
      dark: '/media/examples/dark/ruby.png',
      light: '/media/examples/light/ruby.png',
    },
    summary: 'Require-relative and inheritance fixture with module, class, and method symbols.',
    supported: ['requires', 'classes', 'methods', 'inheritance'],
  },
  {
    id: 'swift',
    href: `${examplesHref}#swift`,
    name: 'Swift',
    category: 'language',
    iconUrl: '/icons/swift.svg',
    workspace: 'examples/example-swift',
    screenshots: {
      dark: '/media/examples/dark/swift.png',
      light: '/media/examples/light/swift.png',
    },
    summary: 'Swift Package module import example with class, protocol, and function symbols.',
    supported: ['modules', 'classes', 'protocols', 'symbols'],
  },
  {
    id: 'dart',
    href: `${examplesHref}#dart`,
    name: 'Dart',
    category: 'language',
    iconUrl: '/icons/dart.svg',
    workspace: 'examples/example-dart',
    screenshots: {
      dark: '/media/examples/dark/dart.png',
      light: '/media/examples/light/dart.png',
    },
    summary: 'Dart package with relative/package imports, model types, runner contracts, and inheritance.',
    supported: ['imports', 'classes', 'mixins', 'inheritance'],
  },
  {
    id: 'rust',
    href: `${examplesHref}#rust`,
    name: 'Rust',
    category: 'language',
    iconUrl: '/icons/rust.svg',
    workspace: 'examples/example-rust',
    screenshots: {
      dark: '/media/examples/dark/rust.png',
      light: '/media/examples/light/rust.png',
    },
    summary: 'Rust module/use example with functions, structs, enums, and traits.',
    supported: ['modules', 'use edges', 'structs', 'traits'],
  },
  {
    id: 'go',
    href: `${examplesHref}#go`,
    name: 'Go',
    category: 'language',
    iconUrl: '/icons/go.svg',
    workspace: 'examples/example-go',
    screenshots: {
      dark: '/media/examples/dark/go.png',
      light: '/media/examples/light/go.png',
    },
    summary: 'Go package/import workspace with functions, receiver methods, structs, interfaces, and constants.',
    supported: ['packages', 'imports', 'methods', 'interfaces'],
  },
  {
    id: 'c',
    href: `${examplesHref}#c`,
    name: 'C',
    category: 'language',
    iconUrl: '/icons/c.svg',
    workspace: 'examples/example-c',
    screenshots: {
      dark: '/media/examples/dark/c.png',
      light: '/media/examples/light/c.png',
    },
    summary: 'Tiny logger with local includes, file-level calls, and C-native symbol nodes.',
    supported: ['includes', 'calls', 'structs', 'typedefs'],
  },
  {
    id: 'cpp',
    href: `${examplesHref}#cpp`,
    name: 'C++',
    category: 'language',
    iconUrl: '/icons/cpp.svg',
    workspace: 'examples/example-cpp',
    screenshots: {
      dark: '/media/examples/dark/cpp.png',
      light: '/media/examples/light/cpp.png',
    },
    summary: 'Task queue runner with namespaces, aliases, templates, inheritance, overrides, includes, and calls.',
    supported: ['includes', 'templates', 'inheritance', 'overrides'],
  },
  {
    id: 'objective-c',
    href: `${examplesHref}#objective-c`,
    name: 'Objective-C',
    category: 'language',
    iconUrl: '/icons/objective-c.svg',
    workspace: 'examples/example-objective-c',
    screenshots: {
      dark: '/media/examples/dark/objective-c.png',
      light: '/media/examples/light/objective-c.png',
    },
    summary: 'UIKit-style controller/store/view example with imports, inheritance, and protocol conformance.',
    supported: ['imports', 'classes', 'protocols', 'inheritance'],
  },
  {
    id: 'pascal',
    href: `${examplesHref}#pascal`,
    name: 'Pascal',
    category: 'language',
    iconUrl: '/icons/pascal.svg',
    workspace: 'examples/example-pascal',
    screenshots: {
      dark: '/media/examples/dark/pascal.png',
      light: '/media/examples/light/pascal.png',
    },
    summary: 'Runner/repository/service/view workspace with unit uses and inheritance.',
    supported: ['units', 'uses', 'classes', 'inheritance'],
  },
  {
    id: 'haskell',
    href: `${examplesHref}#haskell`,
    name: 'Haskell',
    category: 'language',
    iconUrl: '/icons/haskell.svg',
    workspace: 'examples/example-haskell',
    screenshots: {
      dark: '/media/examples/dark/haskell.png',
      light: '/media/examples/light/haskell.png',
    },
    summary: 'Cabal/Haskell project showing module imports, data types, typeclasses, and functions.',
    supported: ['modules', 'data types', 'typeclasses', 'functions'],
  },
  {
    id: 'lua',
    href: `${examplesHref}#lua`,
    name: 'Lua',
    category: 'language',
    iconUrl: '/icons/lua.svg',
    workspace: 'examples/example-lua',
    screenshots: {
      dark: '/media/examples/dark/lua.png',
      light: '/media/examples/light/lua.png',
    },
    summary: 'Lua require-chain example with table and function symbols.',
    supported: ['requires', 'tables', 'functions'],
  },
  {
    id: 'markdown',
    href: `${examplesHref}#markdown`,
    name: 'Markdown',
    category: 'plugin',
    iconUrl: '/icons/markdown.svg',
    workspace: 'examples/example-markdown',
    screenshots: {
      dark: '/media/examples/dark/markdown.png',
      light: '/media/examples/light/markdown.png',
    },
    summary: 'Obsidian-style notes linking to other notes and source files for mixed docs/code graph checks.',
    supported: ['links', 'wikilinks', 'docs/code graph'],
    plugin: { id: 'markdown', packageName: '@codegraphy-dev/plugin-markdown' },
  },
] satisfies readonly ExampleContent[];
