import type { IGraphNodeTypeDefinition } from '../contracts';

export function createCoreSymbolNodeTypes(): IGraphNodeTypeDefinition[] {
  return [
  {
    id: 'symbol',
    label: 'Symbol',
    defaultVisible: false,
  },
  {
    id: 'symbol:function',
    label: 'Function',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['function', 'method'],
  },
  {
    id: 'symbol:namespace',
    label: 'Namespace',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['namespace'],
  },
  {
    id: 'symbol:callable',
    label: 'Callable',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['function'],
  },
  {
    id: 'symbol:method',
    label: 'Method',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['method'],
  },
  {
    id: 'symbol:constructor',
    label: 'Constructor',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['constructor'],
  },
  {
    id: 'symbol:prototype',
    label: 'Prototype',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['prototype'],
  },
  {
    id: 'symbol:class',
    label: 'Class',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['class'],
  },
  {
    id: 'symbol:mixin',
    label: 'Mixin',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['mixin'],
  },
  {
    id: 'symbol:extension',
    label: 'Extension',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['extension'],
  },
  {
    id: 'symbol:interface',
    label: 'Interface',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['interface'],
  },
  {
    id: 'symbol:record',
    label: 'Record',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['record'],
  },
  {
    id: 'symbol:delegate',
    label: 'Delegate',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['delegate'],
  },
  {
    id: 'symbol:property',
    label: 'Property',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['property'],
  },
  {
    id: 'symbol:event',
    label: 'Event',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['event'],
  },
  {
    id: 'symbol:type',
    label: 'Type',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['type'],
  },
  {
    id: 'symbol:struct',
    label: 'Struct',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['struct'],
  },
  {
    id: 'symbol:union',
    label: 'Union',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['union'],
  },
  {
    id: 'symbol:enum',
    label: 'Enum',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['enum'],
  },
  {
    id: 'symbol:typedef',
    label: 'Typedef',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['typedef'],
  },
  {
    id: 'symbol:alias',
    label: 'Alias',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['alias'],
  },
  {
    id: 'symbol:template',
    label: 'Template',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['template'],
  },
  ];
}

export const CORE_SYMBOL_NODE_TYPES: IGraphNodeTypeDefinition[] = createCoreSymbolNodeTypes();
