import type { IGraphNodeTypeDefinition } from '../contracts';

export const CORE_SYMBOL_NODE_TYPES: IGraphNodeTypeDefinition[] = [
  {
    id: 'symbol',
    label: 'Symbol',
    defaultColor: '#7C3AED',
    defaultVisible: false,
  },
  {
    id: 'symbol:function',
    label: 'Function',
    defaultColor: '#8B5CF6',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['function', 'method'],
  },
  {
    id: 'symbol:prototype',
    label: 'Prototype',
    defaultColor: '#A78BFA',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['prototype'],
  },
  {
    id: 'symbol:class',
    label: 'Class',
    defaultColor: '#3B82F6',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['class'],
  },
  {
    id: 'symbol:interface',
    label: 'Interface',
    defaultColor: '#06B6D4',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['interface'],
  },
  {
    id: 'symbol:type',
    label: 'Type',
    defaultColor: '#EC4899',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['type'],
  },
  {
    id: 'symbol:struct',
    label: 'Struct',
    defaultColor: '#0EA5E9',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['struct'],
  },
  {
    id: 'symbol:union',
    label: 'Union',
    defaultColor: '#14B8A6',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['union'],
  },
  {
    id: 'symbol:enum',
    label: 'Enum',
    defaultColor: '#F59E0B',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['enum'],
  },
  {
    id: 'symbol:typedef',
    label: 'Typedef',
    defaultColor: '#F472B6',
    defaultVisible: false,
    parentId: 'symbol',
    matchSymbolKinds: ['typedef'],
  },
];
