import type { IStoreFields } from '../../../../../src/webview/store/messageTypes';

export function createState(
  overrides: Partial<IStoreFields> = {},
): IStoreFields {
  return {
    autoReveal: true,
    graphData: null,
    ghostGraphVisible: false,
    graphRevision: null,
    graphResetVersion: 0,
    pendingFileMutations: {},
    fileMutationError: null,
    graphHasIndex: false,
    graphIndexFreshness: 'missing',
    graphIndexDetail: null,
    graphIsIndexing: false,
    graphIndexProgress: null,
    isLoading: true,
    awaitingInitialBootstrap: false,
    bootstrapComplete: false,
    pendingPluginAssetLoads: 0,
    searchQuery: '',
    searchOptions: { matchCase: false, wholeWord: false, regex: false },
    favorites: new Set<string>(),
    pendingFavoriteSnapshot: null,
    bidirectionalMode: 'separate',
    showOrphans: true,
    directionMode: 'none',
    directionColor: '#ffffff',
    particleSpeed: 0,
    particleSize: 1,
    physicsPaused: false,
    showLabels: true,
    cssSnippets: {},
    graphMode: '2d',
    graphViewportScale: null,
    nodeSizeMode: 'uniform',
    physicsSettings: { repelForce: 10, linkDistance: 80, linkForce: 0.15, damping: 0.7, centerForce: 0.1 },
    depthMode: false,
    depthLimit: 2,
    maxDepthLimit: 10,
    legends: [],
    optimisticLegendUpdates: {},
    optimisticUserLegends: null,
    filterPatterns: [],
    pluginFilterPatterns: [],
    pluginFilterGroups: [],
    disabledCustomFilterPatterns: [],
    disabledPluginFilterPatterns: [],
    respectFilesExclude: true,
    filesExcludedCount: 0,
    dagMode: null,
    pluginStatuses: [],
    graphNodeTypes: [],
    graphEdgeTypes: [],
    nodeColors: {},
    nodeVisibility: {},
    edgeVisibility: {},
    graphScopeProjectionRevision: 0,
    scopeHydrationPending: {},
    nodeDecorations: {},
    nativeNodeDecorations: {},
    edgeDecorations: {},
    pluginContextMenuItems: [],
    pluginExporters: [],
    pluginToolbarActions: [],
    graphViewContributionStatuses: [],
    activePanel: 'none',
    maxFiles: 500,
    verboseDiagnostics: false,
    activeFilePath: null,
    timelineActive: false,
    timelineCommits: [],
    currentCommitSha: null,
    isIndexing: false,
    indexProgress: null,
    isPlaying: false,
    playbackSpeed: 1,
    ...overrides,
  };
}
