import type { CommandExecutionResult } from '../command';

const ROOT_HELP = [
  'CodeGraphy CLI',
  '',
  'Build, shape, and query a CodeGraphy Workspace Relationship Graph.',
  '',
  'Workflow:',
  '  1. Configure graph contributors with Plugins when needed.',
  '  2. Index the complete workspace graph into its Graph Cache.',
  '  3. Shape returned results with Filters and Graph Scope.',
  '  4. Query the resulting graph.',
  '',
  'Workspace commands:',
  '  codegraphy index                         Create or update the Graph Cache',
  '  codegraphy status                        Report Graph Cache freshness',
  '  codegraphy doctor                        Diagnose runtime, settings, cache, and Plugins',
  '',
  'Settings commands:',
  '  codegraphy filter                        Read or change persisted Filters',
  '  codegraphy filter <add|remove> <glob>    Add or remove one Filter pattern',
  '  codegraphy scope                         Read or change persisted Graph Scope',
  '  codegraphy scope node <type> <on|off>    Change one Node Type',
  '  codegraphy scope edge <type> <on|off>    Change one Edge Type',
  '  codegraphy plugins                       Register Plugins and change workspace activity',
  '',
  'Query commands:',
  '  codegraphy nodes                         List Nodes in the shaped graph',
  '  codegraphy search <text>                 Find Nodes by text',
  '  codegraphy edges                         List Relationships in the shaped graph',
  '  codegraphy dependencies <node>           List outgoing Relationships',
  '  codegraphy dependents <node>             List incoming Relationships',
  '  codegraphy path <from> <to>              Find a bounded path between Nodes',
  '  All query commands accept one-off --filter, --node-type, and --edge-type options.',
  '',
  'Global options:',
  '  -C, --workspace <path>  Use another workspace (default: current directory)',
  '  -h, --help              Show help',
  '  -V, --version           Show version',
  '  --verbose               Write diagnostics to stderr',
  '  --                      Treat remaining values as operands',
  '',
  'Automation contract:',
  '  Data is JSON on stdout; failures are JSON on stderr.',
  '  Verbose diagnostics are written only to stderr.',
  '  Exit status: 0 success, 1 operational failure, 2 invalid invocation.',
  '',
  'Run `codegraphy <command> --help` for arguments, effects, output, and examples.',
].join('\n');

const QUERY_PROJECTION_OPTIONS = [
  '  --filter <glob[,glob...]>      Exclude matching paths for this query (repeatable)',
  '  --node-type <type[,type...]>   Include Nodes matching these Node Types (repeatable)',
  '  --edge-type <type[,type...]>   Include only these Edge Types (repeatable)',
  '  These one-off options do not change .codegraphy/settings.json.',
];

const COMMAND_HELP: Record<string, string> = {
  index: [
    'Usage: codegraphy index',
    '',
    'Create or update the workspace Graph Cache.',
    'Indexing stores the complete workspace graph before Filters or Graph Scope.',
    'Enabled Plugins contribute facts during Indexing.',
    '',
    'Effects: Writes .codegraphy/graph.sqlite and workspace index metadata.',
    'Output: JSON indexing summary.',
    'Example: codegraphy index',
  ].join('\n'),
  status: [
    'Usage: codegraphy status',
    '',
    'Report whether the workspace Graph Cache is missing, stale, or fresh.',
    '',
    'Effects: Read-only.',
    'Output: JSON cache status and stale reasons.',
    'Example: codegraphy status',
  ].join('\n'),
  doctor: [
    'Usage: codegraphy doctor',
    '',
    'Check the Node runtime, workspace settings, Graph Cache, and Plugins.',
    '',
    'Effects: Read-only.',
    'Output: JSON checks with recovery actions. Exits nonzero when unhealthy.',
    'Failure envelope: Includes the completed checks in error.details.',
    'Example: codegraphy doctor',
  ].join('\n'),
  nodes: [
    'Usage: codegraphy nodes [--limit <count>] [--offset <count>]',
    '',
    'List Nodes in the graph produced by the persisted workspace settings.',
    '',
    'Effects: Read-only.',
    'Output: Bounded JSON Node results and page metadata.',
    'Options:',
    '  --limit <count>   Maximum results to return (default: 100)',
    '  --offset <count>  Zero-based result offset (default: 0)',
    ...QUERY_PROJECTION_OPTIONS,
    'Example: codegraphy nodes',
  ].join('\n'),
  search: [
    'Usage: codegraphy search [--limit <count>] [--offset <count>] <text>',
    '',
    'Find graph Nodes whose searchable fields contain text.',
    '',
    'Arguments:',
    '  <text>  Text to match in the shaped graph',
    '',
    'Effects: Read-only.',
    'Output: Bounded JSON Node results and page metadata.',
    'Options:',
    '  --limit <count>   Maximum results to return (default: 100)',
    '  --offset <count>  Zero-based result offset (default: 0)',
    ...QUERY_PROJECTION_OPTIONS,
    'Example: codegraphy search SettingsPanel',
  ].join('\n'),
  edges: [
    'Usage: codegraphy edges [--limit <count>] [--offset <count>]',
    '',
    'List Relationships in the graph produced by the persisted workspace settings.',
    '',
    'Effects: Read-only.',
    'Output: Bounded JSON Relationship results and page metadata.',
    'Options:',
    '  --limit <count>   Maximum results to return (default: 100)',
    '  --offset <count>  Zero-based result offset (default: 0)',
    ...QUERY_PROJECTION_OPTIONS,
    'Example: codegraphy edges',
  ].join('\n'),
  dependencies: [
    'Usage: codegraphy dependencies [--limit <count>] [--offset <count>] <node>',
    '',
    'List outgoing Relationships from a file path or exact Node ID.',
    '',
    'Arguments:',
    '  <node>  Workspace-relative file path or exact Node ID',
    '',
    'Effects: Read-only.',
    'Output: Bounded JSON Relationship results and page metadata.',
    'Options:',
    '  --limit <count>   Maximum results to return (default: 100)',
    '  --offset <count>  Zero-based result offset (default: 0)',
    ...QUERY_PROJECTION_OPTIONS,
    'Example: codegraphy dependencies packages/core/src/cli/command.ts',
  ].join('\n'),
  dependents: [
    'Usage: codegraphy dependents [--limit <count>] [--offset <count>] <node>',
    '',
    'List incoming Relationships to a file path or exact Node ID.',
    '',
    'Arguments:',
    '  <node>  Workspace-relative file path or exact Node ID',
    '',
    'Effects: Read-only.',
    'Output: Bounded JSON Relationship results and page metadata.',
    'Options:',
    '  --limit <count>   Maximum results to return (default: 100)',
    '  --offset <count>  Zero-based result offset (default: 0)',
    ...QUERY_PROJECTION_OPTIONS,
    'Example: codegraphy dependents packages/core/src/cli/command.ts',
  ].join('\n'),
  path: [
    'Usage: codegraphy path <from> <to>',
    '',
    'Find a bounded Relationship path between two file paths or exact Node IDs.',
    '',
    'Arguments:',
    '  <from>  Starting workspace-relative file path or exact Node ID',
    '  <to>    Target workspace-relative file path or exact Node ID',
    '',
    'Effects: Read-only.',
    'Output: JSON path result, limits, and `complete` search status.',
    'Options:',
    ...QUERY_PROJECTION_OPTIONS,
    'Example: codegraphy path src/app.ts src/model.ts',
  ].join('\n'),
  scope: [
    'Usage: codegraphy scope [node|edge <type> <on|off>]',
    '',
    'Read or change which Node Types and Edge Types belong to the shaped graph.',
    'Graph Scope is persisted in .codegraphy/settings.json.',
    'Changing Graph Scope does not require reindexing.',
    '',
    'Effects: With no arguments, read-only. A node or edge action writes settings.',
    'Output: JSON Graph Scope state.',
    'Examples:',
    '  codegraphy scope',
    '  codegraphy scope node symbol:function on',
    '  codegraphy scope edge call off',
  ].join('\n'),
  filter: [
    'Usage: codegraphy filter [add|remove <glob>]',
    '',
    'Read or change the workspace path Filters applied by graph queries.',
    'Filters are persisted in .codegraphy/settings.json.',
    'Changing Filters does not require reindexing.',
    '',
    'Effects: With no arguments, read-only. Add and remove write settings.',
    'Output: JSON list of persisted Filter patterns.',
    'Examples:',
    '  codegraphy filter',
    "  codegraphy filter add '**/generated/**'",
    "  codegraphy filter remove '**/generated/**'",
  ].join('\n'),
};

const PLUGIN_HELP: Record<string, string> = {
  register: [
    'Usage: codegraphy plugins register <package>',
    '',
    'Register an installed npm Plugin in the user Plugin Registry.',
    'Effects: Writes ~/.codegraphy/plugins.json.',
    'Output: JSON registered Plugin record.',
    'Example: codegraphy plugins register @codegraphy-dev/plugin-typescript',
  ].join('\n'),
  link: [
    'Usage: codegraphy plugins link <package-root>',
    '',
    'Register a local Plugin checkout for development.',
    'Effects: Writes ~/.codegraphy/plugins.json.',
    'Output: JSON linked Plugin record.',
    'Example: codegraphy plugins link ../my-codegraphy-plugin',
  ].join('\n'),
  list: [
    'Usage: codegraphy plugins list',
    '',
    'List registered Plugins and their activity in this workspace.',
    'Effects: Read-only.',
    'Output: JSON Plugin registry and workspace activity state.',
    'Example: codegraphy plugins list',
  ].join('\n'),
  enable: [
    'Usage: codegraphy plugins enable <plugin-id-or-package>',
    '',
    'Enable a registered Plugin in the workspace settings.',
    'Run `codegraphy index` to include its facts.',
    'Effects: Writes .codegraphy/settings.json.',
    'Output: JSON workspace Plugin state.',
    'Example: codegraphy plugins enable codegraphy.typescript',
  ].join('\n'),
  disable: [
    'Usage: codegraphy plugins disable <plugin-id-or-package>',
    '',
    'Disable a Plugin in the workspace settings.',
    'Run `codegraphy index` to remove its facts.',
    'Effects: Writes .codegraphy/settings.json.',
    'Output: JSON workspace Plugin state.',
    'Example: codegraphy plugins disable codegraphy.typescript',
  ].join('\n'),
};

const PLUGINS_HELP = [
  'Usage: codegraphy plugins <register|link|list|enable|disable>',
  '',
  'Register Plugins globally and change Plugin activity in workspace settings.',
  '',
  'Commands:',
  '  codegraphy plugins register <package>               Register an installed npm Plugin',
  '  codegraphy plugins link <package-root>               Register a local Plugin checkout',
  '  codegraphy plugins list                              List registry and workspace state',
  '  codegraphy plugins enable <plugin-id-or-package>     Enable a workspace Plugin',
  '  codegraphy plugins disable <plugin-id-or-package>    Disable a workspace Plugin',
  '',
  'Run `codegraphy plugins <command> --help` for details.',
].join('\n');

export function createHelpResult(helpPath: string[] = []): CommandExecutionResult {
  const [command, action] = helpPath;
  if (!command) return { exitCode: 0, output: ROOT_HELP };
  if (command === 'plugins' && action) {
    return { exitCode: 0, output: PLUGIN_HELP[action] ?? PLUGINS_HELP };
  }
  if (command === 'plugins') return { exitCode: 0, output: PLUGINS_HELP };
  return { exitCode: 0, output: COMMAND_HELP[command] ?? ROOT_HELP };
}
