interface SerializePerfFixtureSettingsOptions {
  fileCount: number;
  include: readonly string[];
  symbols: boolean;
}

const symbolScopeNodeTypes = [
  'symbol',
  'symbol:function',
  'symbol:namespace',
  'symbol:callable',
  'symbol:method',
  'symbol:constructor',
  'symbol:prototype',
  'symbol:class',
  'symbol:mixin',
  'symbol:extension',
  'symbol:interface',
  'symbol:record',
  'symbol:delegate',
  'symbol:property',
  'symbol:event',
  'symbol:type',
  'symbol:struct',
  'symbol:union',
  'symbol:enum',
  'symbol:typedef',
  'symbol:alias',
  'symbol:template',
  'plugin:codegraphy.gdscript:symbol:scene',
  'plugin:codegraphy.gdscript:symbol:resource',
  'plugin:codegraphy.gdscript:symbol:autoload',
  'plugin:codegraphy.gdscript:symbol:scene-node',
  'plugin:codegraphy.gdscript:symbol:signal',
  'variable',
  'variable:plain',
  'symbol:constant',
  'symbol:global',
  'symbol:field',
  'symbol:parameter',
  'symbol:local',
  'plugin:codegraphy.gdscript:symbol:godot-class-name',
  'plugin:codegraphy.gdscript:symbol:exported-property',
  'plugin:codegraphy.unity:symbol',
  'plugin:codegraphy.unity:symbol:game-object',
  'plugin:codegraphy.unity:symbol:component',
] as const;

const defaultNodeColors = {
  file: '#A1A1AA',
  folder: '#A1A1AA',
  package: '#F59E0B',
  symbol: '#7C3AED',
  'symbol:function': '#8B5CF6',
  'symbol:namespace': '#64748B',
  'symbol:callable': '#8B5CF6',
  'symbol:method': '#A855F7',
  'symbol:constructor': '#C084FC',
  'symbol:prototype': '#A78BFA',
  'symbol:class': '#3B82F6',
  'symbol:mixin': '#2563EB',
  'symbol:extension': '#4F46E5',
  'symbol:interface': '#06B6D4',
  'symbol:record': '#6366F1',
  'symbol:delegate': '#10B981',
  'symbol:property': '#84CC16',
  'symbol:event': '#F97316',
  'symbol:type': '#EC4899',
  'symbol:struct': '#0EA5E9',
  'symbol:union': '#14B8A6',
  'symbol:enum': '#F59E0B',
  'symbol:typedef': '#F472B6',
  'symbol:alias': '#F472B6',
  'symbol:template': '#C084FC',
  'plugin:codegraphy.gdscript:symbol:scene': '#478CBF',
  'plugin:codegraphy.gdscript:symbol:resource': '#F59E0B',
  'plugin:codegraphy.gdscript:symbol:autoload': '#10B981',
  'plugin:codegraphy.gdscript:symbol:scene-node': '#A855F7',
  'plugin:codegraphy.gdscript:symbol:signal': '#EF4444',
  variable: '#14B8A6',
  'variable:plain': '#14B8A6',
  'symbol:constant': '#22C55E',
  'symbol:global': '#0D9488',
  'symbol:field': '#84CC16',
  'symbol:parameter': '#2DD4BF',
  'symbol:local': '#10B981',
  'plugin:codegraphy.gdscript:symbol:godot-class-name': '#478CBF',
  'plugin:codegraphy.gdscript:symbol:exported-property': '#2DD4BF',
  'plugin:codegraphy.unity:symbol': '#F97316',
  'plugin:codegraphy.unity:symbol:game-object': '#0EA5E9',
  'plugin:codegraphy.unity:symbol:component': '#22C55E',
} as const;

function createNodeVisibility(symbols: boolean): Record<string, boolean> {
  const visibility = Object.fromEntries(
    Object.keys(defaultNodeColors).map(nodeType => [nodeType, nodeType === 'file']),
  );
  if (symbols) {
    for (const nodeType of symbolScopeNodeTypes) visibility[nodeType] = true;
  }
  return visibility;
}

export function serializePerfFixtureSettings(
  options: SerializePerfFixtureSettingsOptions,
): string {
  const settings = {
    version: 1,
    maxFiles: options.fileCount,
    verboseDiagnostics: false,
    include: [...options.include],
    respectGitignore: true,
    showOrphans: true,
    cssSnippets: {},
    plugins: [
      { id: 'codegraphy.markdown', enabled: true },
      { id: 'codegraphy.typescript', enabled: true },
    ],
    pluginData: {},
    nodeColors: { ...defaultNodeColors },
    nodeVisibility: createNodeVisibility(options.symbols),
    edgeVisibility: {
      include: true,
      import: true,
      using: true,
      type: false,
      reference: false,
      call: false,
      'type-import': false,
      inherit: false,
      implements: false,
      event: false,
      load: false,
      nests: true,
      contains: false,
      overrides: false,
      'codegraphy.gdscript:signal-connection': false,
    },
    favorites: [],
    bidirectionalEdges: 'separate',
    legend: [],
    legendVisibility: {},
    legendOrder: [],
    filterPatterns: [],
    disabledCustomFilterPatterns: [],
    disabledPluginFilterPatterns: [],
    showLabels: true,
    directionMode: 'arrows',
    directionColor: '#475569',
    particleSpeed: 0.005,
    particleSize: 4,
    depthMode: false,
    depthLimit: 1,
    dagMode: null,
    nodeSizeMode: 'connections',
    physics: {
      repelForce: 10,
      linkDistance: 80,
      linkForce: 0.15,
      damping: 0.7,
      centerForce: 0.1,
      chargeRange: 200,
    },
    timeline: {
      maxCommits: 500,
      playbackSpeed: 1,
    },
  };

  return `${JSON.stringify(settings, null, 2)}\n`;
}
