import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { acceptanceStepExpressions } from '../steps';
import type { AcceptanceStepExpression } from '../graphView/steps';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export const CUCUMBER_STEPS_PATH = path.join(__dirname, 'steps.ts');

const HEADER = `// Generated by tests/acceptance/cucumber/generator.ts.
// Editor-only Cucumber step declarations for alexkrechik.cucumberautocomplete.
// The executable acceptance registry lives in ../steps.ts.
// Run pnpm --filter @codegraphy-dev/extension run generate:cucumber-steps after changing step text.

export {};

declare const Step: (expression: string | RegExp) => void;
`;

export function formatCucumberSteps(expressions: AcceptanceStepExpression[]): string {
  const declarations = expressions
    .map(formatStepDeclaration)
    .join('\n');

  return `${HEADER}\n${declarations}\n`;
}

function formatStepDeclaration(expression: AcceptanceStepExpression): string {
  if (typeof expression === 'string') {
    return `Step(${JSON.stringify(expression)});`;
  }

  return `Step(${expression.toString()});`;
}

function main(): void {
  const nextContent = formatCucumberSteps(acceptanceStepExpressions);
  const checkOnly = process.argv.includes('--check');

  if (checkOnly) {
    const currentContent = fs.existsSync(CUCUMBER_STEPS_PATH)
      ? fs.readFileSync(CUCUMBER_STEPS_PATH, 'utf8')
      : '';

    if (currentContent !== nextContent) {
      throw new Error('Cucumber step declarations are stale. Run generate:cucumber-steps.');
    }

    return;
  }

  fs.writeFileSync(CUCUMBER_STEPS_PATH, nextContent);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
