import type { GraphStateFields } from './state';
import { DEFAULT_PHYSICS, DEFAULT_SEARCH_OPTIONS } from './defaults';
import { DEFAULT_DIRECTION_COLOR } from '../../shared/fileColors';
import { DEFAULT_MAX_FILES } from '../../shared/settings/defaults';

export const INITIAL_STATE: GraphStateFields = {
  graphData: null,
  graphHasIndex: false,
  graphIndexFreshness: 'missing' as const,
  graphIndexDetail: null,
  graphIsIndexing: false,
  graphIndexProgress: null,
  isLoading: true,
  awaitingInitialBootstrap: false,
  bootstrapComplete: false,
  pendingPluginAssetLoads: 0,
  searchQuery: '',
  searchOptions: DEFAULT_SEARCH_OPTIONS,
  favorites: new Set<string>(),
  pendingFavoriteSnapshot: null,
  bidirectionalMode: 'separate' as const,
  showOrphans: true,
  directionMode: 'arrows' as const,
  directionColor: DEFAULT_DIRECTION_COLOR,
  particleSpeed: 0.005,
  particleSize: 4,
  showLabels: true,
  cssSnippets: {},
  graphViewportScale: null,
  nodeSizeMode: 'connections' as const,
  physicsSettings: DEFAULT_PHYSICS,
  depthMode: false,
  depthLimit: 1,
  maxDepthLimit: 10,
  legends: [],
  optimisticLegendUpdates: {},
  optimisticUserLegends: null,
  filterPatterns: [],
  pluginFilterPatterns: [],
  pluginFilterGroups: [],
  disabledCustomFilterPatterns: [],
  disabledPluginFilterPatterns: [],
  dagMode: null,
  pluginStatuses: [],
  graphNodeTypes: [],
  graphEdgeTypes: [],
  nodeColors: {},
  nodeVisibility: {},
  edgeVisibility: {},
  nodeDecorations: {},
  edgeDecorations: {},
  pluginContextMenuItems: [],
  pluginExporters: [],
  pluginToolbarActions: [],
  graphViewContributionStatuses: [],
  expandedGroupId: null,
  activePanel: 'none' as const,
  maxFiles: DEFAULT_MAX_FILES,
  showFps: false,
  verboseDiagnostics: false,
  activeFilePath: null,
};
